### ISSUE TITLE
Grenades don't hurt other people

### ISSUE THREAD

**Issue by niclaslindstedt** [hifi/qwsv-lua#21]
You can still take damage from your own grenades

**Comment by niclaslindstedt** [comment]
The function CanDamage(targ, inflictor) (line 35ish in combat.lua) is the culprit.

**Comment by niclaslindstedt** [comment]
It seems the traceline function in qwsv is the real culprit. It returns a trace_fraction that is 1 for the owner of the grenade, but it's not 1 for other people, but anywhere between 0 and 0.99.

**Comment by hifi** [comment]
I would start by comparing the raw `trace_fraction` in `PR_traceline` with as much percision as possible in both PR1 an Lua, then if they are equal, see if the PR1 one has been rounded and if the Lua one hasn't.

The fix could be rounding that PR1 could be doing implicitly somewhere which needs to be tested and verified before doing anything like that for the Lua code. PR1 `ftos()` and `vtos()` functions only show one decimal accuracy so it might be that.

Also if that rounding is happening and we need to emulate it, it might be better to do it on Lua side so we can keep the extra percision unless `trace_fraction` is the only place where it matters, then it could be done in `PR_traceline` before returning back to Lua.

**Comment by hifi** [comment]
Commit 23e049f fixed this.
